name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Xrd Mod
        path: |
          target/i686-pc-windows-msvc/release/rev2hook.dll
